# Accepted strings for the last word in the location name (first word if scientific).
---
- "Africa"
- "Albania"
- "Algeria"
- "Antarctica"
- "Argentina"
- "Asia"
- "Australia"
- "Austria"
- "Bahamas"
- "Belize"
- "Bolivia"
- "Brazil"
- "Bulgaria"
- "Cambodia"
- "Canada"
- "Chile"
- "China"
- "Colombia"
- "Costa Rica"
- "Croatia"
- "Czech Republic"
- "Dominican Republic"
- "Ecuador"
- "England"
- "Europe"
- "Finland"
- "France"
- "Germany"
- "Greece"
- "Hungary"
- "India"
- "Indonesia"
- "Iran"
- "Ireland"
- "Israel"
- "Italy"
- "Japan"
- "Kenya"
- "Lebanon"
- "Macedonia"
- "Malaysia"
- "Mexico"
- "Morocco"
- "Namibia"
- "Netherlands"
- "New Zealand"
- "North America"
- "Northern Ireland"   # (if we recognize England and Wales and Scotland...)
- "Norway"
- "Panama"
- "Philippines"
- "Poland"
- "Portugal"
- "Russia"
- "Scotland"
- "Slovenia"
- "South America"
- "South Africa"
- "South Korea"
- "Spain"
- "Sweden"
- "Switzerland"
- "Taiwan"
- "Tanzania"
- "Thailand"
- "Turkey"
- "USA"
- "Wales"

