# Allowed strings in the second position; interpretation varies according to
# country. 
---
Argentina:
- "Buenos Aires"
- "Catamarca"
- "Chaco"
- "Chubut"
- "Córdoba"
- "Corrientes"
- "Entre Ríos"
- "Formosa"
- "Jujuy"
- "La Pampa"
- "La Rioja"
- "Mendoza"
- "Misiones"
- "Neuquén"
- "Río Negrob"
- "Salta"
- "San Juan"
- "San Luis"
- "Santa Cruz"
- "Santa Fe"
- "Santiago del Estero"
- "Tierra del Fuego"
- "Tucumán"

Australia:
- "Australian Capital Territory"
- "New South Wales"
- "Northern Territory"
- "Queensland"
- "South Australia"
- "Tasmania"
- "Victoria"
- "Western Australia"

Brazil:
- "Acre"
- "Alagoas"
- "Amapá"
- "Amazonas"
- "Bahia"
- "Ceará"
- "Distrito Federal"
- "Espírito Santo"
- "Goiás"
- "Maranhão"
- "Mato Grosso"
- "Mato Grosso do Sul"
- "Minas Gerais"
- "Pará"
- "Paraíba"
- "Paraná"
- "Pernambuco"
- "Piauí"
- "Rio de Janeiro"
- "Rio Grande do Norte"
- "Rio Grande do Sul"
- "Rondônia"
- "Roraima"
- "Santa Catarina"
- "São Paulo"
- "Sergipe"
- "Tocantins"

Canada:
- "Alberta"
- "British Columbia"
- "Labrador"
- "Manitoba"
- "New Brunswick"
- "Newfoundland"
- "Newfoundland and Labrador"
- "Nova Scotia"
- "Ontario"
- "Prince Edward Island"
- "Quebec"
- "Saskatchewan"
- "Northwest Territories"
- "Nunavut"
- "Yukon"

Chile:
- "Aisén"
- "Antofagasta"
- "Araucanía"
- "Arica y Parinacota"
- "Atacama"
- "Biobío"
- "Coquimbo"
- "Los Lagos"
- "Los Ríos"
- "Magallanes"
- "Maule"
- "O'Higgins"
- "Tarapacá"
- "Valparaíso"

England:
- "Bedfordshire"
- "Berkshire"
- "Buckinghamshire"
- "Cambridgeshire"
- "Cheshire"
- "Cornwall"
- "Cumbria"
- "Derbyshire"
- "Devon"
- "Dorset"
- "Durham"
- "East Sussex"
- "East Yorkshire"
- "Essex"
- "Gloucestershire"
- "Greater London"
- "Greater Manchester"
- "Hampshire"
- "Herefordshire"
- "Hertfordshire"
- "Isle of Wight"
- "Kent"
- "Lancashire"
- "Leicestershire"
- "Lincolnshire"
- "Merseyside"
- "Norfolk"
- "North Yorkshire"
- "Northamptonshire"
- "Northumberland"
- "Nottinghamshire"
- "Oxfordshire"
- "Rutland"
- "Shropshire"
- "Somerset"
- "South Yorkshire"
- "Staffordshire"
- "Suffolk"
- "Surrey"
- "Tyne and Wear"
- "Warwickshire"
- "West Midlands"
- "West Sussex"
- "West Yorkshire"
- "Wiltshire"
- "Worcestershire"

Mexico:
- "Aguascalientes"
- "Baja California"
- "Baja California Sur"
- "Campeche"
- "Chiapas"
- "Chihuahua"
- "Coahuila"
- "Colima"
- "Distrito Federal"
- "Durango"
- "Guanajuato"
- "Guerrero"
- "Hidalgo"
- "Jalisco"
- "Mexico"
- "Michoacan"
- "Morelos"
- "Nayarit"
- "Nuevo Leon"
- "Oaxaca"
- "Puebla"
- "Queretaro"
- "Quintana Roo"
- "San Luis Potosi"
- "Sinaloa"
- "Sonora"
- "Tabasco"
- "Tamaulipas"
- "Tlaxcala"
- "Veracruz"
- "Yucatan"
- "Zacatecas"

USA:
- "Alabama"
- "Alaska"
- "American Samoa"
- "Arizona"
- "Arkansas"
- "California"
- "Colorado"
- "Connecticut"
- "Delaware"
- "Federated States of Micronesia"
- "Florida"
- "Georgia"
- "Guam"
- "Hawaii"
- "Idaho"
- "Illinois"
- "Indiana"
- "Iowa"
- "Kansas"
- "Kentucky"
- "Louisiana"
- "Maine"
- "Marshall Islands"
- "Maryland"
- "Massachusetts"
- "Michigan"
- "Minnesota"
- "Mississippi"
- "Missouri"
- "Montana"
- "Nebraska"
- "Nevada"
- "New England"
- "New Hampshire"
- "New Jersey"
- "New Mexico"
- "New York"
- "North Carolina"
- "North Dakota"
- "Northern Mariana Islands"
- "Ohio"
- "Oklahoma"
- "Oregon"
- "Pacific Northwest"
- "Palau"
- "Pennsylvania"
- "Puerto Rico"
- "Rhode Island"
- "South Carolina"
- "South Dakota"
- "Tennessee"
- "Texas"
- "Utah"
- "Vermont"
- "Virgin Islands"
- "Virginia"
- "Washington"
- "Washington DC"
- "West Virginia"
- "Wisconsin"
- "Wyoming"

