# Supply the Google Maps API keys for your application here.

development:
 localhost:             ABQIAAAAoN4H8SiH1m-X7s5V1JXxShT2ak2DffiooUuokG88BHgj3ApF7hQZ0izPoWKf-D-qu7OoDrdn5mf_2w
 localhost.localdomain: AIzaSyDtr0wCknVQ9Sob4e6xdTzN5V8zie1WCz0

test:
 localhost:             ABQIAAAAoN4H8SiH1m-X7s5V1JXxShT2ak2DffiooUuokG88BHgj3ApF7hQZ0izPoWKf-D-qu7OoDrdn5mf_2w
 localhost.localdomain: AIzaSyDtr0wCknVQ9Sob4e6xdTzN5V8zie1WCz0

production:
 localhost:             ABQIAAAAoN4H8SiH1m-X7s5V1JXxShT2ak2DffiooUuokG88BHgj3ApF7hQZ0izPoWKf-D-qu7OoDrdn5mf_2w
 localhost.localdomain: AIzaSyDtr0wCknVQ9Sob4e6xdTzN5V8zie1WCz0
 mushroomobserver.org:  ABQIAAAAoN4H8SiH1m-X7s5V1JXxShTByWbZcAHEOi8Om5ex78pQduqBbBSZ0rpYLs5r7cUI2tzHNDgAUlBA3w
 allfungi.ru:           ABQIAAAAzMUFFnT9uH0Sfg98Y4kbhGFJQa0g3IQ9GZqIMmInSLrthJKGDmlRT98f4j135zat56yjRKQlWnkmod3TB
