# Supply the Google Maps API keys for your application here.

development:
 localhost:             "AIzaSyBAuQWe-V-LB1C9fDeQnAOjbPxot0cm044"
 localhost.localdomain: "AIzaSyBAuQWe-V-LB1C9fDeQnAOjbPxot0cm044"

test:
 localhost:             "AIzaSyBAuQWe-V-LB1C9fDeQnAOjbPxot0cm044"
 localhost.localdomain: "AIzaSyBAuQWe-V-LB1C9fDeQnAOjbPxot0cm044"

production:
 localhost:             "AIzaSyBAuQWe-V-LB1C9fDeQnAOjbPxot0cm044"
 localhost.localdomain: "AIzaSyBAuQWe-V-LB1C9fDeQnAOjbPxot0cm044"
 mushroomobserver.org:  "AIzaSyDN412tyXjZnYM586hIxRjn7WOURvmeGio"
